config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'welcome/index' #Dashboard
    resources :admins   #  Administradores  
    resources :subjects #  Assuntos/Areas
    resources :questions #  Perguntas

  end

  namespace :users_backoffice do
    get 'welcome/index'
  end

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'

    post 'answer', to: 'answer#question'  
  end

  devise_for :users
  devise_for :admins
  root to: 'site/welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject,  inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  max_paginates_per 5

  #metodo de classe
  # def self.search(term,page) 
  #   includes(:answers)
  #           .where("lower(description) LIKE ?", "%#{term.downcase}%")
  #           .page(page)
  # end

  # def self.last_question(page)
  #   includes(:answers).order('created_at desc').page(page)
  # end

  #Scopes
    scope :search, -> (term,page){ 
    includes(:answers, :subject)
            .where("lower(description) LIKE ?", "%#{term.downcase}%")
            .page(page)
    }

    scope :last_question, -> (page){
      includes(:answers).order('created_at desc').page(page)
    }

    scope :_search_subject_, -> (subject_id,page){ 
    includes(:answers)
            .where(subject_id: subject_id)
            .page(page)
    }

end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update,:create]
  before_action :set_admin, only: [:edit,:update, :destroy]
  def index
    @admins = Admin.all.page params[:page]
  end  

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(set_params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path
      flash[:success] = "Object successfully created"
    else
      render :new
      flash[:error] = "Something went wrong"

    end
  end  
  def edit;end

  def update
    @admin = Admin.find(params[:id])
    if @admin.update set_params_admin
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso"
    else
      render :edit
    end
    
  end

  def destroy
    @admin = Admin.find(params[:id])
    if @admin.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to admins_backoffice_admins_path
    else
      flash[:error] = 'Something went wrong'
      render :index
    end
  end
  

  private
  def set_params_admin
    params.require(:admin).permit(:email,:password,:password_confirmation)
  end
  
  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password,:password_confirmation)
    end   
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit,:update, :destroy]
  before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject)
                          .order(:description)
                          .page(params[:page])
  end  

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path  notice: " Questao Criada com sucesso"
     
    else
      render :new
      flash[:error] = "Something went wrong"

    end
  end  
  def edit;end

  def update
    @question = Question.find(params[:id])
    if @question.update params_question
      redirect_to admins_backoffice_questions_path, notice: "Questao atualizada com sucesso"
    else
      render :edit
    end
    
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to admins_backoffice_questions_path
    else
      flash[:error] = 'Something went wrong'
      render :index
    end
  end
  

  private
  def params_question
    params.require(:question).permit(:description, :subject_id,
      answers_attributes: [:id, :description, :correct, :_destroy])
  end
  
  

  def set_question
    @question = Question.find(params[:id])
  end
  
  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit,:update, :destroy]
  def index

    @subjects = Subject.all.page params[:page] 

  end  

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path  notice: "Assunto/Área Criado com sucesso"
     
    else
      render :new
      flash[:error] = "Something went wrong"

    end
  end  
  def edit;end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update params_subject
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso"
    else
      render :edit
    end
    
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to admins_backoffice_subjects_path
    else
      flash[:error] = 'Something went wrong'
      render :index
    end
  end
  

  private
  def params_subject
    params.require(:subject).permit(:description)
  end
  
  

  def set_subject
    @subject = Subject.find(params[:id])
  end

end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  # skip_before_action :verify_authenticity_token, :only => :create
  # skip_before_action :verify_authenticity_token, :only => :destroy
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      puts "Informe os parametros corretamente"
    end
  end
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
   <%= f.label :description %> </br>
   <%= f.text_field :description %>
   <%= f.check_box :correct %> Correta?

   <%= link_to_remove_association('Remover', f) %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
                      locals:{action_message:'Editando'} %>

app/views/admins_backoffice/questions/index.html.erb
<%if flash[:notice]%>
  <div class = "alert alert-success" role "alert">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%=flash[:notice]%>
  </div>
<%end%> 


<div class="container-fluid">
    <div class="row mb-6">
      <h2><%=t('messages.listing', model: @questions.model_name.human(count: 2))%></h2>
    </div>    
  </div>

<div class="card-body table-responsive p-0">
<table class="table table-hover text-nowrap">
    <thead>
      <tr>
        <th>ID</th>
        <th><%= translate_attribute(@questions,:description)%></th>
        <th><%= translate_attribute(@questions ,:subject)%></th>
        
        <th>
          <%=link_to new_admins_backoffice_question_path, class: 'btn btn-success btn-circle' do%>
          <i class="fa fa-plus"></i> Novo
          <%end%>
        </th>

      </tr>
    </thead>
      <tbody>
        
        <% @questions.each do |question|%>
            <tr>
              <td><%=question.id%></td>
              <td><%=question.description.truncate(50)%></td>
              <td><%=question.subject.description.truncate(30)%></td>

              
              <td>        
                  <%=link_to edit_admins_backoffice_question_path(question.id), class: 'btn btn-primary' do%>
                    <i class="fas fa-edit"></i> Edit
                  <%end%>
              </td>

              <td>
                <%=link_to admins_backoffice_question_path(question.id),method: :delete, class: 'btn btn-danger',data:{confirm: t('messages.confirm_with', item: question.description.truncate(15))} do%>
                  <i class="fas fa-trash"></i> Del
                <%end%>
              </td>

            </tr>
          <%end%>   
      </tbody>
  </table>

   <div class = "d-flex justify-content-center"> 
    <%= paginate @questions %>
  </div>

 

</div

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
                      locals:{action_message:'Novo'}%>