config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'welcome/index' #Dashboard
    resources :admins   #  Administradores  
    resources :subjects #  Assuntos/Areas
    resources :questions #  Perguntas

  end

  namespace :users_backoffice do
    get 'welcome/index'
  end

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'

    post 'answer', to: 'answer#question'  
  end

  devise_for :users
  devise_for :admins
  root to: 'site/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  max_paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject,  inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  max_paginates_per 5

  #metodo de classe
  # def self.search(term,page) 
  #   includes(:answers)
  #           .where("lower(description) LIKE ?", "%#{term.downcase}%")
  #           .page(page)
  # end

  # def self.last_question(page)
  #   includes(:answers).order('created_at desc').page(page)
  # end

  #Scopes
    scope :search, -> (term,page){ 
    includes(:answers, :subject)
            .where("lower(description) LIKE ?", "%#{term.downcase}%")
            .page(page)
    }

    scope :last_question, -> (page){
      includes(:answers).order('created_at desc').page(page)
    }

    scope :_search_subject_, -> (subject_id,page){ 
    includes(:answers)
            .where(subject_id: subject_id)
            .page(page)
    }

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  # skip_before_action :verify_authenticity_token, :only => :create
  # skip_before_action :verify_authenticity_token, :only => :destroy
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, :only => :create
  skip_before_action :verify_authenticity_token, :only => :destroy

  layout :layout_by_resource

  protected
  def layout_by_resource
    #condicional ternaria  
     devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
    
  end
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question
    @answer = Answer.find(params[:answer_id])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    # @questions = Question.includes(:answers).page params[:page]
    @questions = Question.search(params[:term], params[:page])
  end
   def subject
    @questions = Question._search_subject_(params[:subject_id], params[:page])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions =  Question.last_question(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'

end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController  
  before_action :authenticate_user!

  layout 'users_backoffice'

end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      puts "Informe os parametros corretamente"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
  
  def msg_jumbotron
    case params[:action]
      when 'index'
        "Últimas perguntas cadastradas"
      when 'questions'
        "Resultados para o termo \"#{params[:term]}\"..."
      when 'subject'
        "Mostrando questões para o assunto \"#{params[:subject]}\"..."
    end

  end


end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/_users/_control_sidebar.html.erb
 <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>

app/views/_users/_footer.html.erb
 <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

app/views/_users/_header.html.erb
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <%# <a href="index3.html" class="nav-link">Home</a> %>
        <%=link_to 'Home', site_welcome_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      
      <!-- Notifications Dropdown Menu -->
      
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
      </li>
      
    
     <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Sair<span class="caret"></span></a>
            <ul class="dropdown-menu">            

              <!-- this dropdown menu item (a logout form) does not -->
                <li>

                  <%if user_signed_in?%>
                    
                    <%= link_to 'Log off', destroy_user_session_path, method: :delete, class:"nav-item "%>

                  <%end%>       
              
              </li>
            </ul>
          </li>
        </ul>
</div

    </ul>

    
    


  </nav>
  <!-- /.navbar -->

app/views/_users/_sidebar.html.erb
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <%# <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" %>
        <%=image_tag 'AdminLTELogo.png',class:"brand-image img-circle elevation-3",alt:"AdminLTE Logo", style:"opacity: .8"%>
           
           <%# style="opacity: .8"> %>
      <span class="brand-text font-weight-light">User-BackOffice</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <%# <img src="app/assets/images/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> %>
          <%=image_tag 'user2-160x160.jpg',class:"img-circle elevation-2",alt:"User Image"%>
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            
            <%# <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Active Page</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Inactive Page</p>
                </a>
              </li>
            </ul> %>
          </li>
          <%# <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Simple Link
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li> %>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>